"""initial schema — events, pos_transactions, store_layouts

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-31

Hand-authored (not autogenerated) so the migration matches `app/infra/models.py`
exactly and stays portable across SQLite + Postgres for testing and prod.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── events ─────────────────────────────────────────────────────────
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("store_id", sa.String(length=64), nullable=False),
        sa.Column("camera_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("track_id", sa.String(length=128), nullable=True),
        sa.Column("person_id", sa.String(length=128), nullable=True),
        sa.Column("zone_id", sa.String(length=64), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=True),
        sa.Column("group_size", sa.Integer(), nullable=True),
        sa.Column("bbox", sa.JSON(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("event_id", name="uq_events_event_id"),
    )
    op.create_index("ix_events_event_id", "events", ["event_id"], unique=False)
    op.create_index("ix_events_event_type", "events", ["event_type"], unique=False)
    op.create_index("ix_events_store_id", "events", ["store_id"], unique=False)
    op.create_index("ix_events_timestamp", "events", ["timestamp"], unique=False)
    op.create_index("ix_events_track_id", "events", ["track_id"], unique=False)
    op.create_index("ix_events_person_id", "events", ["person_id"], unique=False)
    op.create_index("ix_events_zone_id", "events", ["zone_id"], unique=False)
    op.create_index("ix_events_is_staff", "events", ["is_staff"], unique=False)
    op.create_index("ix_events_store_ts", "events", ["store_id", "timestamp"], unique=False)
    op.create_index(
        "ix_events_store_zone_ts", "events", ["store_id", "zone_id", "timestamp"], unique=False
    )

    # ── pos_transactions ───────────────────────────────────────────────
    op.create_table(
        "pos_transactions",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("txn_id", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("basket_inr", sa.Numeric(12, 2), nullable=False),
        sa.UniqueConstraint("store_id", "txn_id", name="uq_pos_store_txn"),
    )
    op.create_index("ix_pos_store_id", "pos_transactions", ["store_id"], unique=False)
    op.create_index("ix_pos_timestamp", "pos_transactions", ["timestamp"], unique=False)
    op.create_index("ix_pos_store_ts", "pos_transactions", ["store_id", "timestamp"], unique=False)

    # ── store_layouts ──────────────────────────────────────────────────
    op.create_table(
        "store_layouts",
        sa.Column("store_id", sa.String(length=64), primary_key=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("store_layouts")
    op.drop_index("ix_pos_store_ts", table_name="pos_transactions")
    op.drop_index("ix_pos_timestamp", table_name="pos_transactions")
    op.drop_index("ix_pos_store_id", table_name="pos_transactions")
    op.drop_table("pos_transactions")
    op.drop_index("ix_events_store_zone_ts", table_name="events")
    op.drop_index("ix_events_store_ts", table_name="events")
    op.drop_index("ix_events_is_staff", table_name="events")
    op.drop_index("ix_events_zone_id", table_name="events")
    op.drop_index("ix_events_person_id", table_name="events")
    op.drop_index("ix_events_track_id", table_name="events")
    op.drop_index("ix_events_timestamp", table_name="events")
    op.drop_index("ix_events_store_id", table_name="events")
    op.drop_index("ix_events_event_type", table_name="events")
    op.drop_index("ix_events_event_id", table_name="events")
    op.drop_table("events")
